# Pandas Data Analysis Practice

This notebook explores Pandas Series and DataFrames, data selection, adding data, statistical analysis, CSV files and data cleaning.

In [1]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

## 1. Create a DataFrame

A DataFrame stores data in rows and columns, similar to a spreadsheet or database table.

In [3]:
data = {
    "Name": ["Amira", "Adam", "Sara", "Youssef", "Lina"],
    "Age": [22, 25, 21, 28, 24],
    "Country": ["UK", "France", "UK", "Spain", "France"],
    "Score": [85, 78, 92, 67, 88]
}

df = pd.DataFrame(data)

display(df)

      Name  Age Country  Score
0    Amira   22      UK     85
1     Adam   25  France     78
2     Sara   21      UK     92
3  Youssef   28   Spain     67
4     Lina   24  France     88

## 2. Exploring a DataFrame

Pandas provides methods and attributes to help us understand the structure and contents of a dataset.

In [5]:
print("First five rows:")
display(df.head())

First five rows:

      Name  Age Country  Score
0    Amira   22      UK     85
1     Adam   25  France     78
2     Sara   21      UK     92
3  Youssef   28   Spain     67
4     Lina   24  France     88

In [6]:
print("DataFrame dimensions (rows, columns):")
print(df.shape)

DataFrame dimensions (rows, columns):
(5, 4)

In [7]:
print("Column names:")
print(df.columns)

Column names:
Index(['Name', 'Age', 'Country', 'Score'], dtype='str')

In [8]:
print("Data types and non-null values:")
df.info()

Data types and non-null values:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Age      5 non-null      int64
 2   Country  5 non-null      str
 3   Score    5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [9]:
print("Summary statistics:")
display(df.describe())

Summary statistics:

             Age      Score
count   5.000000   5.000000
mean   24.000000  82.000000
std     2.738613   9.823441
min    21.000000  67.000000
25%    22.000000  78.000000
50%    24.000000  85.000000
75%    25.000000  88.000000
max    28.000000  92.000000

## 3. Selecting Data

Pandas allows us to select individual columns, multiple columns and particular rows.

In [11]:
print("Select one column:")
display(df["Name"])

Select one column:

0      Amira
1       Adam
2       Sara
3    Youssef
4       Lina
Name: Name, dtype: str

In [12]:
print("Select multiple columns:")
display(df[["Name", "Score"]])

Select multiple columns:

      Name  Score
0    Amira     85
1     Adam     78
2     Sara     92
3  Youssef     67
4     Lina     88

In [13]:
print("Select the first two rows:")
display(df.iloc[0:2])

Select the first two rows:

    Name  Age Country  Score
0  Amira   22      UK     85
1   Adam   25  France     78

In [14]:

print("Select the first row using its position:")
display(df.iloc[0])

Select the first row using its position:

Name       Amira
Age           22
Country       UK
Score         85
Name: 0, dtype: object

In [15]:
print("Select rows where the score is above 80:")
display(df[df["Score"] > 80])

Select rows where the score is above 80:

    Name  Age Country  Score
0  Amira   22      UK     85
2   Sara   21      UK     92
4   Lina   24  France     88

In [16]:
print("Select rows using a condition:")
display(df.loc[df["Country"] == "UK"])

Select rows using a condition:

    Name  Age Country  Score
0  Amira   22      UK     85
2   Sara   21      UK     92

## 4. Adding Data

We can add a new column or add a new row to an existing DataFrame.

In [17]:
df["Passed"] = df["Score"] >= 70

df.loc[len(df)] = {
    "Name": "Omar",
    "Age": 23,
    "Country": "UK",
    "Score": 74,
    "Passed": True
}

display(df)

      Name  Age Country  Score  Passed
0    Amira   22      UK     85    True
1     Adam   25  France     78    True
2     Sara   21      UK     92    True
3  Youssef   28   Spain     67   False
4     Lina   24  France     88    True
5     Omar   23      UK     74    True

## 5. Statistical Analysis

Pandas provides functions to calculate totals, averages, minimums, maximums and other useful statistics.

In [18]:
print("Average age:", df["Age"].mean())
print("Average score:", df["Score"].mean())
print("Highest score:", df["Score"].max())
print("Lowest score:", df["Score"].min())
print("Total scores:", df["Score"].sum())
print("Number of records:", df["Name"].count())

print("Number of people in each country:")
display(df["Country"].value_counts())

Average age: 23.833333333333332
Average score: 80.66666666666667
Highest score: 92
Lowest score: 67
Total scores: 484
Number of records: 6
Number of people in each country:

Country
UK        3
France    2
Spain     1
Name: count, dtype: int64

## 6. Working with CSV Files

CSV stands for Comma-Separated Values. It is a common file format for storing tabular data.

Pandas uses `to_csv()` to save data and `read_csv()` to load it.

In [19]:
df.to_csv("customers.csv", index=False)

customers_df = pd.read_csv("customers.csv")

display(customers_df)

      Name  Age Country  Score  Passed
0    Amira   22      UK     85    True
1     Adam   25  France     78    True
2     Sara   21      UK     92    True
3  Youssef   28   Spain     67   False
4     Lina   24  France     88    True
5     Omar   23      UK     74    True

## 7. Data Cleaning

Real datasets can contain missing values, duplicate rows and incorrect data types. Pandas provides methods to identify and correct these problems.

In [20]:
messy_data = {
    "Name": ["Amira", "Adam", "Sara", "Adam", None],
    "Age": [22, 25, None, 25, 30],
    "Score": [85, 78, 92, 78, None]
}

messy_df = pd.DataFrame(messy_data)

display(messy_df)

    Name   Age  Score
0  Amira  22.0   85.0
1   Adam  25.0   78.0
2   Sara   NaN   92.0
3   Adam  25.0   78.0
4    NaN  30.0    NaN

In [21]:
print("Missing values per column:")
print(messy_df.isnull().sum())

print("Number of duplicate rows:")
print(messy_df.duplicated().sum())

clean_df = messy_df.drop_duplicates().copy()

clean_df["Age"] = clean_df["Age"].fillna(clean_df["Age"].mean())
clean_df["Score"] = clean_df["Score"].fillna(clean_df["Score"].mean())
clean_df["Name"] = clean_df["Name"].fillna("Unknown")

print("Cleaned DataFrame:")
display(clean_df)

print("Missing values after cleaning:")
print(clean_df.isnull().sum())

Missing values per column:
Name     1
Age      1
Score    1
dtype: int64
Number of duplicate rows:
1
Cleaned DataFrame:

      Name        Age  Score
0    Amira  22.000000   85.0
1     Adam  25.000000   78.0
2     Sara  25.666667   92.0
4  Unknown  30.000000   85.0

Missing values after cleaning:
Name     0
Age      0
Score    0
dtype: int64