In [1]:
import numpy as np
import pandas as pd

### CSV Files in Pandas

Download the iris dataset through the terminal in the same folder as this note book use curl

In [8]:
import os

print(os.getcwd())
print(os.listdir())

/Users/salmameziane/PycharmProjects/data-606/Week5
['Working_With_Data.ipynb', 'Learning_Pandas.ipynb', 'iris.csv', '.ipynb_checkpoints']

In [10]:
df = pd.read_csv('iris.csv')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [11]:
# I am displaying the first ten rows so I can get a better look at the data.
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [12]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [14]:
# I am saving a copy of the DataFrame to a new CSV file.
# index=False stops Pandas from saving the row index as an extra column.
df.to_csv('iris_copy.csv', index=False)

In [15]:
# I am grouping the flowers by species and finding the average numerical measurements.
df.groupby('species').mean(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [16]:
# I am going through each row and printing the species and petal length.
# iterrows() gives me each row's index and its data.
for index, row in df.iterrows():
    print(index, row['species'], row['petal_length'])

0 setosa 1.4
1 setosa 1.4
2 setosa 1.3
3 setosa 1.5
4 setosa 1.4
5 setosa 1.7
6 setosa 1.4
7 setosa 1.5
8 setosa 1.4
9 setosa 1.5
10 setosa 1.5
11 setosa 1.6
12 setosa 1.4
13 setosa 1.1
14 setosa 1.2
15 setosa 1.5
16 setosa 1.3
17 setosa 1.4
18 setosa 1.7
19 setosa 1.5
20 setosa 1.7
21 setosa 1.5
22 setosa 1.0
23 setosa 1.7
24 setosa 1.9
25 setosa 1.6
26 setosa 1.6
27 setosa 1.5
28 setosa 1.4
29 setosa 1.6
30 setosa 1.6
31 setosa 1.5
32 setosa 1.5
33 setosa 1.4
34 setosa 1.5
35 setosa 1.2
36 setosa 1.3
37 setosa 1.5
38 setosa 1.3
39 setosa 1.5
40 setosa 1.3
41 setosa 1.3
42 setosa 1.3
43 setosa 1.6
44 setosa 1.9
45 setosa 1.4
46 setosa 1.6
47 setosa 1.4
48 setosa 1.5
49 setosa 1.4
50 versicolor 4.7
51 versicolor 4.5
52 versicolor 4.9
53 versicolor 4.0
54 versicolor 4.6
55 versicolor 4.5
56 versicolor 4.7
57 versicolor 3.3
58 versicolor 4.6
59 versicolor 3.9
60 versicolor 3.5
61 versicolor 4.2
62 versicolor 4.0
63 versicolor 4.7
64 versicolor 3.6
65 versicolor 4.4
66 versicolor 4.5
67 versicolor 4.1
68 versicolor 4.5
69 versicolor 3.9
70 versicolor 4.8
71 versicolor 4.0
72 versicolor 4.9
73 versicolor 4.7
74 versicolor 4.3
75 versicolor 4.4
76 versicolor 4.8
77 versicolor 5.0
78 versicolor 4.5
79 versicolor 3.5
80 versicolor 3.8
81 versicolor 3.7
82 versicolor 3.9
83 versicolor 5.1
84 versicolor 4.5
85 versicolor 4.5
86 versicolor 4.7
87 versicolor 4.4
88 versicolor 4.1
89 versicolor 4.0
90 versicolor 4.4
91 versicolor 4.6
92 versicolor 4.0
93 versicolor 3.3
94 versicolor 4.2
95 versicolor 4.2
96 versicolor 4.2
97 versicolor 4.3
98 versicolor 3.0
99 versicolor 4.1
100 virginica 6.0
101 virginica 5.1
102 virginica 5.9
103 virginica 5.6
104 virginica 5.8
105 virginica 6.6
106 virginica 4.5
107 virginica 6.3
108 virginica 5.8
109 virginica 6.1
110 virginica 5.1
111 virginica 5.3
112 virginica 5.5
113 virginica 5.0
114 virginica 5.1
115 virginica 5.3
116 virginica 5.5
117 virginica 6.7
118 virginica 6.9
119 virginica 5.0
120 virginica 5.7
121 virginica 4.9
122 virginica 6.7
123 virginica 4.9
124 virginica 5.7
125 virginica 6.0
126 virginica 4.8
127 virginica 4.9
128 virginica 5.6
129 virginica 5.8
130 virginica 6.1
131 virginica 6.4
132 virginica 5.6
133 virginica 5.1
134 virginica 5.6
135 virginica 6.1
136 virginica 5.6
137 virginica 5.5
138 virginica 4.8
139 virginica 5.4
140 virginica 5.6
141 virginica 5.1
142 virginica 5.1
143 virginica 5.9
144 virginica 5.7
145 virginica 5.2
146 virginica 5.0
147 virginica 5.2
148 virginica 5.4
149 virginica 5.1

In [17]:
# I am using this to get a quick statistical summary of the numerical columns.
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [18]:
# I am ranking petal length from smallest to largest.
# The smallest petal length gets rank 1.
df['petal_length_rank'] = df['petal_length'].rank(method='min', ascending=True).astype(int)

# I am sorting by the new rank to check the result.
df.sort_values('petal_length_rank').head(10)

,sepal_length,sepal_width,petal_length,petal_width,species,petal_length_rank
22,4.6,3.6,1.0,0.2,setosa,1
13,4.3,3.0,1.1,0.1,setosa,2
14,5.8,4.0,1.2,0.2,setosa,3
35,5.0,3.2,1.2,0.2,setosa,3
36,5.5,3.5,1.3,0.2,setosa,5
40,5.0,3.5,1.3,0.3,setosa,5
38,4.4,3.0,1.3,0.2,setosa,5
42,4.4,3.2,1.3,0.2,setosa,5
2,4.7,3.2,1.3,0.2,setosa,5
41,4.5,2.3,1.3,0.3,setosa,5

In [19]:
# I am finding the average numerical measurements for each species.
mean_by_species = df.groupby('species').mean(numeric_only=True)
mean_by_species

,sepal_length,sepal_width,petal_length,petal_width,petal_length_rank
species,,,,,
setosa,5.006,3.418,1.464,0.244,21.36
versicolor,5.936,2.770,4.260,1.326,74.78
virginica,6.588,2.974,5.552,2.026,123.12

In [20]:
# I am making a separate DataFrame for each species.
# This lets me look at each group on its own.
setosa_df = df[df['species'] == 'setosa'].copy()
versicolor_df = df[df['species'] == 'versicolor'].copy()
virginica_df = df[df['species'] == 'virginica'].copy()

print('Setosa:', setosa_df.shape)
print('Versicolor:', versicolor_df.shape)
print('Virginica:', virginica_df.shape)

Setosa: (50, 6)
Versicolor: (50, 6)
Virginica: (50, 6)

In [21]:
# I am creating one DataFrame with the sepal measurements for all species.
sepal_info = df[['sepal_length', 'sepal_width', 'species']].copy()
sepal_info.head()

   sepal_length  sepal_width species
0           5.1          3.5  setosa
1           4.9          3.0  setosa
2           4.7          3.2  setosa
3           4.6          3.1  setosa
4           5.0          3.6  setosa

In [22]:
# I am creating another DataFrame with the petal measurements for all species.
petal_info = df[['petal_length', 'petal_width', 'species']].copy()
petal_info.head()

   petal_length  petal_width species
0           1.4          0.2  setosa
1           1.4          0.2  setosa
2           1.3          0.2  setosa
3           1.5          0.2  setosa
4           1.4          0.2  setosa

In [23]:
# I am adding an ID for each flower so the sepal and petal details can be matched correctly.
iris_with_id = df.reset_index(names='flower_id')

sepal_info = iris_with_id[['flower_id', 'sepal_length', 'sepal_width', 'species']].copy()
petal_info = iris_with_id[['flower_id', 'petal_length', 'petal_width', 'species']].copy()

# I am merging the two DataFrames using the flower ID.
merged_df = pd.merge(
    sepal_info,
    petal_info,
    on='flower_id',
    suffixes=('_sepal', '_petal')
)

# Both DataFrames contain species, so I am dropping the repeated species column.
# The merged result keeps species_sepal and species_petal; they contain the same values.
merged_df = merged_df.drop(columns=['species_petal']).rename(columns={'species_sepal': 'species'})

merged_df.head()

   flower_id  sepal_length  sepal_width species  petal_length  petal_width
0          0           5.1          3.5  setosa           1.4          0.2
1          1           4.9          3.0  setosa           1.4          0.2
2          2           4.7          3.2  setosa           1.3          0.2
3          3           4.6          3.1  setosa           1.5          0.2
4          4           5.0          3.6  setosa           1.4          0.2

In [24]:
# I am joining the three species DataFrames back together.
iris_concatenated = pd.concat(
    [setosa_df, versicolor_df, virginica_df],
    ignore_index=True
)

# I am checking the result and comparing its shape with the original dataset.
print('Original shape:', df.shape)
print('Concatenated shape:', iris_concatenated.shape)
iris_concatenated.head()

Original shape: (150, 6)
Concatenated shape: (150, 6)

,sepal_length,sepal_width,petal_length,petal_width,species,petal_length_rank
0,5.1,3.5,1.4,0.2,setosa,12
1,4.9,3.0,1.4,0.2,setosa,12
2,4.7,3.2,1.3,0.2,setosa,5
3,4.6,3.1,1.5,0.2,setosa,24
4,5.0,3.6,1.4,0.2,setosa,12

In [27]:
%pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (2.5.4)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.0.6)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.11.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

In [28]:
import seaborn as sns

In [29]:
flights = sns.load_dataset('flights')

flights.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [30]:
# I am checking how many rows and columns the dataset has.
flights.shape

(144, 3)

In [31]:
flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        144 non-null    int64
 1   month       144 non-null    category
 2   passengers  144 non-null    int64
dtypes: category(1), int64(2)
memory usage: 2.9 KB

In [32]:
flights['year'].unique(), flights['month'].unique()

(array([1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959,
        1960]),
 ['Jan', 'Feb', 'Mar', 'Apr', 'May', ..., 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
 Length: 12
 Categories (12, str): ['Jan', 'Feb', 'Mar', 'Apr', ..., 'Sep', 'Oct', 'Nov', 'Dec'])

In [33]:
flights_wide = flights.pivot(
    index='year',
    columns='month',
    values='passengers'
)

flights_wide.head()

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201

In [34]:
flights_stacked = flights_wide.stack()
flights_stacked.head()

year  month
1949  Jan      112
      Feb      118
      Mar      132
      Apr      129
      May      121
dtype: int64

In [35]:
flights_unstacked = flights_stacked.unstack()
flights_unstacked.head()

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949   112  118  132  129  121  135  148  148  136  119  104  118
1950   115  126  141  135  125  149  170  170  158  133  114  140
1951   145  150  178  163  172  178  199  199  184  162  146  166
1952   171  180  193  181  183  218  230  242  209  191  172  194
1953   196  196  236  235  229  243  264  272  237  211  180  201

In [36]:
pd.crosstab(flights['year'], flights['month'])

month  Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949     1    1    1    1    1    1    1    1    1    1    1    1
1950     1    1    1    1    1    1    1    1    1    1    1    1
1951     1    1    1    1    1    1    1    1    1    1    1    1
1952     1    1    1    1    1    1    1    1    1    1    1    1
1953     1    1    1    1    1    1    1    1    1    1    1    1
1954     1    1    1    1    1    1    1    1    1    1    1    1
1955     1    1    1    1    1    1    1    1    1    1    1    1
1956     1    1    1    1    1    1    1    1    1    1    1    1
1957     1    1    1    1    1    1    1    1    1    1    1    1
1958     1    1    1    1    1    1    1    1    1    1    1    1
1959     1    1    1    1    1    1    1    1    1    1    1    1
1960     1    1    1    1    1    1    1    1    1    1    1    1

In [37]:
# I load the Titanic dataset from Seaborn.
titanic = sns.load_dataset('titanic')

# I display the first five rows.
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [38]:
titanic.shape

(891, 15)

In [39]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [40]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [41]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [42]:
titanic.duplicated().sum()

np.int64(107)

In [43]:
titanic['class'].value_counts()

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [44]:
titanic_clean = titanic.copy()

In [45]:
# I remove exact duplicate rows.
titanic_clean = titanic_clean.drop_duplicates()

# I check how many duplicate rows remain.
titanic_clean.duplicated().sum()

np.int64(0)

In [46]:
titanic_clean.isnull().sum()

survived         0
pclass           0
sex              0
age            106
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           582
embark_town      2
alive            0
alone            0
dtype: int64

In [47]:
# I fill missing ages with the median age.
titanic_clean['age'] = titanic_clean['age'].fillna(
    titanic_clean['age'].median()
)

# I fill missing embarkation ports with the most common port.
titanic_clean['embarked'] = titanic_clean['embarked'].fillna(
    titanic_clean['embarked'].mode()[0]
)

# I remove columns that I will not use in this analysis.
titanic_clean = titanic_clean.drop(columns=['deck', 'embark_town'])

# I check the remaining missing values.
titanic_clean.isnull().sum()

survived      0
pclass        0
sex           0
age           0
sibsp         0
parch         0
fare          0
embarked      0
class         0
who           0
adult_male    0
alive         0
alone         0
dtype: int64

In [48]:
# I group passengers by class and calculate their average fare and age.
class_averages = titanic_clean.groupby('class', observed=True).agg(
    average_fare=('fare', 'mean'),
    average_age=('age', 'mean')
)

class_averages

        average_fare  average_age
class
First      84.487812    36.947056
Second     21.835404    29.838364
Third      13.656223    25.718321

In [49]:
# I calculate each passenger's fare as a percentage of all fares combined.
total_fare = titanic_clean['fare'].sum()

titanic_clean['fare_percentage'] = (
    titanic_clean['fare'] / total_fare
) * 100

# I display the fare and its percentage of the total.
titanic_clean[['fare', 'fare_percentage']].head()

      fare  fare_percentage
0   7.2500         0.026641
1  71.2833         0.261936
2   7.9250         0.029121
3  53.1000         0.195120
4   8.0500         0.029580

In [50]:
survivors_by_sex = titanic_clean[
    titanic_clean['survived'] == 1
].groupby('sex').size()

survivors_by_sex

sex
female    217
male      106
dtype: int64

In [51]:
# I calculate the survival rate for female and male passengers.
survival_by_sex = titanic_clean.groupby('sex', observed=True).agg(
    passengers=('survived', 'count'),
    survivors=('survived', 'sum'),
    survival_rate=('survived', 'mean')
)

# I convert the survival rate into a percentage.
survival_by_sex['survival_rate'] = (
    survival_by_sex['survival_rate'] * 100
).round(2)

survival_by_sex

        passengers  survivors  survival_rate
sex
female         293        217          74.06
male           491        106          21.59

In [52]:
survivors_by_class = titanic_clean.groupby(
    'class', observed=True
)['survived'].agg(['count', 'sum', 'mean'])

survivors_by_class.columns = [
    'passengers', 'survivors', 'survival_rate'
]

# I convert the survival rate into a percentage.
survivors_by_class['survival_rate'] = (
    survivors_by_class['survival_rate'] * 100
).round(2)

survivors_by_class

        passengers  survivors  survival_rate
class
First          214        135          63.08
Second         165         84          50.91
Third          405        104          25.68

In [53]:
# I create a column to separate children from adults.
titanic_clean['age_group'] = np.where(
    titanic_clean['age'] < 18,
    'Child',
    'Adult'
)

# I compare survival rates between children and adults.
age_survival = titanic_clean.groupby('age_group').agg(
    passengers=('survived', 'count'),
    survivors=('survived', 'sum'),
    survival_rate=('survived', 'mean')
)

age_survival['survival_rate'] = (
    age_survival['survival_rate'] * 100
).round(2)

age_survival

           passengers  survivors  survival_rate
age_group
Adult             674        263          39.02
Child             110         60          54.55

In [54]:
port_survival = titanic_clean.groupby('embarked', observed=True).agg(
    passengers=('survived', 'count'),
    survivors=('survived', 'sum'),
    survival_rate=('survived', 'mean')
)

port_survival['survival_rate'] = (
    port_survival['survival_rate'] * 100
).round(2)

port_survival

          passengers  survivors  survival_rate
embarked
C                155         90          58.06
Q                 59         20          33.90
S                570        213          37.37

In [55]:
titanic_clean.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone,fare_percentage,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False,0.026641,Adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False,0.261936,Adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True,0.029121,Adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False,0.195120,Adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True,0.029580,Adult

In [56]:
print("Dataset shape:", titanic_clean.shape)
print("\nMissing values:")
print(titanic_clean.isnull().sum())

Dataset shape: (784, 15)

Missing values:
survived           0
pclass             0
sex                0
age                0
sibsp              0
parch              0
fare               0
embarked           0
class              0
who                0
adult_male         0
alive              0
alone              0
fare_percentage    0
age_group          0
dtype: int64